---
all:
  hosts:
    test:
      ansible_host: 3.121.22.114
  children:
    newservers:
      hosts:
        test:
      vars:
        ansible_become: true
        ansible_ssh_private_key_file: ~/.ssh/ssh.pem
        ansible_user: ubuntu
        encrypt_disk_name: /dev/xvdb
