# roles/enable_performance_cpu/tasks/main.yml
---
- name: Check current CPU governor
  ansible.builtin.command: cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  register: cpu_governor
  changed_when: false

- name: Display current CPU governor
  ansible.builtin.debug:
    msg: "Current CPU governor: {{ cpu_governor.stdout_lines }}"

- name: Set CPU governor to performance
  ansible.builtin.shell: |
    for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
      echo 'performance' > $cpu
    done
  when: "'performance' not in cpu_governor.stdout"
  changed_when: false

- name: Add performance parameters to GRUB configuration
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash noacpi  cpufreq.default_governor=perfomance"
    mode: "0600"
  notify:
    - Update GRUB

- name: Verify CPU governor has been set to performance
  ansible.builtin.command: cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  register: new_cpu_governor
  changed_when: false

- name: Display new CPU governor
  ansible.builtin.debug:
    msg: "New CPU governor: {{ new_cpu_governor.stdout_lines }}"
