---
- name: Get the current active network interface
  ansible.builtin.set_fact:
    current_interface_name: "{{ ansible_default_ipv4.interface }}"

- name: Information about interface
  ansible.builtin.debug:
    var: ansible_facts[current_interface_name]

- name: Check if the current interface name is already renamed
  ansible.builtin.debug:
    msg: The active network interface is already named {{ network_interface_rename_new_interface_name }}.
  when: current_interface_name == network_interface_rename_new_interface_name

- name: Change interface name
  when: current_interface_name != network_interface_rename_new_interface_name
  block:
    - name: Capturing Existing Configuration
      ansible.builtin.stat:
        path: "{{ network_interface_rename_netplan_config }}"
      register: netplan_config
      failed_when: not netplan_config.stat.exists

    - name: Update netplan configuration with new interface name
      ansible.builtin.lineinfile:
        path: "{{ network_interface_rename_netplan_config }}"
        regexp: "^(\\s*)set-name: {{ current_interface_name }}.*"
        line: "\\1set-name: {{ network_interface_rename_new_interface_name }}"
        state: present
        backup: true
        backrefs: true

    - name: Apply netplan configuration
      ansible.builtin.command: netplan apply
      register: netplan_apply
      changed_when: netplan_apply.rc != 0

    - name: Get the current network interface from default route
      ansible.builtin.command: ip route show default
      register: route_output
      changed_when: false

    - name: Parse the renamed network interface from route output
      ansible.builtin.set_fact:
        renamed_interface: "{{ route_output.stdout | regex_search(network_interface_rename_new_interface_name) }}"

    - name: Check if the network interface was successfully renamed
      ansible.builtin.fail:
        msg: "Network interface rename failed: expected {{ network_interface_rename_new_interface_name }}"
      when: renamed_interface == ""

    - name: Display the renamed network interface name
      ansible.builtin.debug:
        msg: The network interface is now named {{ renamed_interface }}
