# roles/network_interface_rename/tasks/main.yml
---
- name: Get the current active network interface
  shell: ip -o route show default | awk '{print $5}'
  register: active_interface
  changed_when: false

- name: Set the active network interface name
  set_fact:
    current_interface_name: "{{ active_interface.stdout.strip() }}"

- name: Check if the current interface name is already
  fail:
    msg: "The active network interface is already named {{ new_interface_name }}."
  when: current_interface_name == new_interface_name

- name: Check if netplan configuration file exists
  stat:
    path: "{{ netplan_config_path }}"
  register: netplan_check

- name: Update netplan configuration with new interface name using sed
  command: >
    sed -i 's/set-name: {{ current_interface_name }}/set-name: {{ new_interface_name }}/' {{ netplan_config_path }}
  when: netplan_check.stat.exists and current_interface_name != new_interface_name

- name: Apply netplan configuration
  command: netplan apply

- name: Check if the network interface was successfully renamed
  shell: ip -o route show default | awk '{print $5}'
  register: renamed_interface
  failed_when: renamed_interface.stdout.strip() != "{{ new_interface_name }}"
  changed_when: false

- name: Display the renamed network interface name
  debug:
    msg: "The network interface is now named {{ renamed_interface.stdout.strip() }}"
