# roles/encrypt_near_root_part/defaults/main.yml
---
- name: Name root disk
  ansible.builtin.command: lsblk -no MOUNTPOINT,NAME
  register: root_disk_output
  changed_when: false

- name: Extract name root disk
  ansible.builtin.set_fact:
    root_disk: "{{ root_disk_output.stdout_lines | select('match', '^/ ') | map('regex_replace', '^/ ', '') | first }}"

- name: Find partition
  ansible.builtin.command: lsblk -no NAME,MOUNTPOINT
  register: target_partition_output
  changed_when: false

- name: Extract target partittion
  ansible.builtin.set_fact:
    target_partition: >
      /dev/{{
        target_partition_output.stdout_lines
        | select('match', '^xvda[0-9]+$')
        | first
      }}

- name: Check partition
  ansible.builtin.fail:
    msg: Not found partition
  when: target_partition_output.stdout == ""

- name: Encrypt the disk with LUKS
  ansible.builtin.command: >
    echo "{{ encrypt_near_root_part_luks_password }}" |
    cryptsetup luksFormat {{ target_partition }} --key-file -
  args:
    creates: /dev/mapper/encrypted_partition
  register: luks_format
  ignore_errors: true

- name: Open the encrypted disk
  ansible.builtin.command: >
    echo "{{ encrypt_near_root_part_luks_password }}" |
    cryptsetup open {{ target_partition }} encrypted_partition --key-file -
  register: cryptsetup_open
  failed_when: cryptsetup_open.rc != 0
  changed_when: cryptsetup_open.rc != 0
  no_log: true
