---
- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: true
  notify:
    - Reboot

- name: Reload cpufrequtils
  ansible.builtin.systemd_service:
    name: cpufrequtils
    state: reloaded
    enabled: true
    daemon_reload: true

- name: Reboot
  ansible.builtin.reboot:
  when:
    auto-reboot: true
