---
- name: Encrypt the second disk in the system
  hosts: all
  become: true
  tags: encrypt
  pre_tasks:
    - name: Set disk name
      ansible.builtin.set_fact:
        encrypt_partition_partition_name: "{{ encrypt_disk_name }}"
  roles:
    - role: encrypt_partition

- name: Encrypt partition next to root
  hosts: all
  become: true
  tags: encrypt
  gather_facts: false
  pre_tasks:
    - name: Run lsblk to get block devices and labels
      command: "lsblk -o NAME,MOUNTPOINT,LABEL -J"
      register: lsblk_output
      changed_when: false

    - name: Parse lsblk output
      set_fact:
        lsblk_devices: "{{ lsblk_output.stdout | from_json }}"

    - name: Find the device with root mountpoint
      set_fact:
        rootfs_device: >
          {{
            lsblk_devices.blockdevices | selectattr('children', 'defined') |
            map(attribute='children') |
            select('search', 'cloudimg-rootfs') | first
          }}

    - name: Find index of rootfs device
      set_fact:
        root_index: > 
          {{ lookup('ansible.utils.index_of', (rootfs_device | map(attribute='mountpoint')), 'eq', '/') }}

    - name: Find the next disk
      set_fact:
        next_disk: "{{ rootfs_device[root_index | int + 1]}}"

    - name: Show next disk
      debug:
        msg: "Next disk is: {{ next_disk }}"

    - name: Set disk name
      ansible.builtin.set_fact:
        encrypt_partition_partition_name: "/dev/{{ next_disk.name }}"
  roles:
    - role: encrypt_partition

- name: Rename network interfaces
  hosts: all
  become: true
  tags: network
  roles:
    - role: network_interface_rename

- name: CPU performance improvements
  hosts: all
  become: true
  tags: performance
  roles:
    - role: enable_performance_cpu

- name: Print CPU info
  hosts: all
  become: true
  tags: cpu_info
  tasks:
    - name: Get list of CPUs
      ansible.builtin.command: lscpu
      register: lscpu_output
      changed_when: false

    - name: Show list of CPUs
      ansible.builtin.debug:
        msg: "{{ lscpu_output.stdout.split('\n') }}"

    - name: Display Hyper-Threading information
      ansible.builtin.debug:
        msg: "{{ 'Hyper-Threading enabled' if (ansible_facts.processor_threads_per_core | int) > 1 else 'Hyper-Threading is not enabled' }}"
