# roles/disable_c_state/tasks/main.yml
---
- name: Add noacpi parameter to GRUB configuration
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash noacpi processor.max_cstate=0"
    mode: "0600"
  notify:
    - Update GRUB

- name: Copy script c-states
  ansible.builtin.copy:
    src: set_disable_c_state.sh
    dest: /tmp/set_disable_c_state.sh
    mode: "0755"

- name: Execute c-states
  ansible.builtin.command:
    cmd: /tmp/set_disable_c_state.sh
  become: true
